[tool.poetry]
name = "iscc-crypto"
version = "0.1.0"
description = "ISCC - Crypto"
authors = ["Titusz <tp@py7.de>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
keyring = "^23.5.0"
jcs = "^0.1.0"
jwcrypto = "^1.0"
loguru = "^0.5.3"
didkit = "^0.3.1"
rfc3161ng = "^2.1.3"
asn1crypto = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
